---

- hosts: q_cloud
  remote_user: root
  tasks:
    - name: deploy gsc1...
      docker_container:
        name: gsc1
        image: yy194131/gogsc:{{image_tag}}
        state: started
        pull: true
        restart: true
        restart_policy: always
        env:
          wxAppId: "{{wxAppId}}"
          wxappSecret: "{{wxappSecret}}"
          listenAddr: "{{listenAddr}}"
          mysqlDSN: "{{mysqlDSN}}"
          md5Secret: "{{md5Secret}}"
          alipayAppId: "{{alipayAppId}}"
          alipayRsa: "{{alipayRsa}}"
        published_ports:
          - "8081:8080"
    
    - name: deploy gsc2...
      docker_container:
        name: gsc2
        image: yy194131/gogsc:{{image_tag}}
        state: started
        pull: true
        restart: true
        restart_policy: always
        env:
          wxAppId: "{{wxAppId}}"
          wxappSecret: "{{wxappSecret}}"
          listenAddr: "{{listenAddr}}"
          mysqlDSN: "{{mysqlDSN}}"
          md5Secret: "{{md5Secret}}"
          alipayAppId: "{{alipayAppId}}"
          alipayRsa: "{{alipayRsa}}"
        published_ports:
          - "8082:8080"
