---

- hosts: q_cloud
  remote_user: root
  tasks:
    - name: deploy gsc1...
      docker_container:
        name: gsc1
        image: registry.cn-beijing.aliyuncs.com/roselle-1/gogsc:{{image_tag}}
        state: started
        pull: true
        restart: true
        restart_policy: always
        env:
          wxAppId: "{{wxAppId}}"
          wxAppSecret: "{{wxAppSecret}}"
          qqAppId: "{{qqAppId}}"
          qqAppSecret: "{{qqAppSecret}}"
          listenAddr: "{{listenAddr}}"
          mysqlDSN: "{{mysqlDSN}}"
          md5Secret: "{{md5Secret}}"
          alipayAppId: "{{alipayAppId}}"
          alipayRsa: "{{alipayRsa}}"
          audioSecret: "{{audioSecret}}"
          audioDomain: "{{audioDomain}}"
        published_ports:
          - "8081:8080"
        volumes:
          - /etc/localtime:/etc/localtime:ro

    - name: deploy gsc2...
      docker_container:
        name: gsc2
        image: registry.cn-beijing.aliyuncs.com/roselle-1/gogsc:{{image_tag}}
        state: started
        pull: true
        restart: true
        restart_policy: always
        env:
          wxAppId: "{{wxAppId}}"
          wxAppSecret: "{{wxAppSecret}}"
          qqAppId: "{{qqAppId}}"
          qqAppSecret: "{{qqAppSecret}}"
          listenAddr: "{{listenAddr}}"
          mysqlDSN: "{{mysqlDSN}}"
          md5Secret: "{{md5Secret}}"
          alipayAppId: "{{alipayAppId}}"
          alipayRsa: "{{alipayRsa}}"
          audioSecret: "{{audioSecret}}"
          audioDomain: "{{audioDomain}}"
        published_ports:
          - "8082:8080"
        volumes:
          - /etc/localtime:/etc/localtime:ro
