FROM golang:1.24-alpine AS builder

RUN apk add --no-cache git make gcc musl-dev

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -ldflags '-extldflags "-static"' -o myapp main.go

FROM alpine:latest

RUN mkdir -p /gogsc

COPY dict.txt comic.ttf go.sum ./

# 从构建阶段复制生成的二进制文件
COPY --from=builder /app/myapp /gogsc/myapp

WORKDIR /gogsc

CMD ["/gogsc/myapp"]
