FROM golang:1.24-alpine AS builder

RUN apk add --no-cache git make gcc musl-dev

WORKDIR /app

COPY go.mod go.sum ./

RUN GOPROXY='https://goproxy.cn,direct' go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -ldflags '-extldflags "-static"' -o myapp main.go

FROM alpine:latest

RUN mkdir -p /gogsc

WORKDIR /gogsc

COPY dict.txt comic.ttf ./

COPY --from=builder /app/myapp /gogsc/myapp

CMD ["/gogsc/myapp"]
