CREATE TABLE `USER_LIKE_GSC` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `OPEN_ID` VARCHAR(128) NOT NULL,
  `GSC_ID` INT(11) NOT NULL,
  `CREATE_TIME` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  KEY `IDX_OPEN_ID` (`OPEN_ID`,`GSC_ID`)
) ENGINE = INNODB DEFAULT CHARSET = UTF8MB4;
