name: Build docker & Deploy to remote machines

on:
  push:
    tags: ['release-*.*.*']

jobs:
  build:
    runs-on: ubuntu-18.04
    environment: deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Test
        run: |
          go vet
          go test -v ./...

      - name: Build
        run: go build -o gsc .

      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v2.1.0
        with:
          registry: https://registry.cn-beijing.aliyuncs.com
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: registry.cn-beijing.aliyuncs.com/roselle-1/gogsc:${{ env.RELEASE_VERSION }}

  deploy:
    runs-on: ubuntu-18.04
    needs: build
    environment: deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          name: id_rsa
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Copy key file
        run: cp /home/runner/.ssh/id_rsa .

      - name: Execute Ansible Playbook
        uses: saubermacherag/ansible-playbook-docker-action@v1.4
        with:
          playbookName: "ansible.yaml"
          verbosity: "vv"
          KeyFile: "id_rsa"
          extraVars: "-e ANSIBLE_HOST_KEY_CHECKING=False -e wxAppId=${{secrets.WXAPPID}} -e wxAppSecret=${{secrets.WXAPPSECRET}} -e mysqlDSN=${{secrets.MYSQLDSN}} -e listenAddr=${{secrets.LISTENADDR}} -e image_tag=${{ env.RELEASE_VERSION }} -e md5Secret=${{secrets.MD5SECRET}}  -e alipayAppId=${{secrets.ALIPAYAPPID}} -e alipayRsa=${{secrets.ALIPAYRSA}}  -e audioSecret=${{secrets.AUDIOSECRET}}  -e audioDomain=${{secrets.AUDIODOMAIN}}  -e qqAppId=${{secrets.QQAPPID}} -e qqAppSecret=${{secrets.QQAPPSECRET}}  -i hosts"
