name: Deploy to remote machines

on:
  push:
    tags: ['release-*.*.*']

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
  build:
    needs: checkout
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: yy194131/gogsc

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: '49.234.18.99'

      - name: Install ansible & Fire
        env:
          IMAGE_TAG: ${{build.steps.meta.outputs.tags}}
          wxAppId: ${{secrets.WXAPPID}}
          wxappSecret: ${{secrets.WXAPPSECRET}}
          mysqlDSN: ${{secrets.MYSQLDSN}}
          listenAddr: ${{secrets.LISTENADDR}}
        run: |
          ssh-keyscan -H '49.234.18.99' >> ~/.ssh/known_hosts
          echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
          sudo apt install python -y
          sudo pip install -r requirements.txt
          sudo chmod 755 deploy.sh
          bash deploy.sh
